### ISSUE TITLE
Pls. show dry-run output in a modal dialogue

### ISSUE THREAD

**Issue by yvesio** [jbeyerstedt/kirby-widget-rsync_publishing#4]
Our latest Kirby project has around 400 pages for a single language. Therefore it takes quiet some scrolling to reach the end of the page to finalize the publishing run. Since the 400 pages take some time for the dry-run and the publishing it would be good to give some indication in the modal dialogue that something is happening.

So far for know and great plugin. THX a lot.

**Comment by jbeyerstedt** [comment]
I would implement something, that the output field does not "explode", but has a maximum size and a scrollbar.

A "real time" output of the rsync script is a bit more complicated, because it requires some  communication between the browser and the server. I don´t know how to achieve this with the kirby backend.
But if you want to try this, please fork and submit a pull request.
